apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
  labels:
    app: devops-project # This matches your ServiceMonitor selector
spec:
  selector:
    app: devops-project
  ports:
    - name: http # Must match the 'port' name in monitor.yaml
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer